[JBPM-10012] - Right Springboot version should be 2.3.10
kiegroup/droolsjbpm-build-bootstrap pull request #1886
Opened 2022-02-04 10:00 UTC by afalhambra

**Thank you for submitting this pull request**

**[JBPM-10012](https://issues.redhat.com/browse/JBPM-10012)**: Right Springboot version should be 2.3.10

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
 
* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`
    
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2022-02-04 10:13 UTC, gmunozfe requested changes

2022-02-04 10:13 UTC, gmunozfe commented on pom.xml
>      <version.org.springframework.amqpboot>2.3.4</version.org.springframework.amqpboot>
```suggestion
    <version.org.springframework.amqpboot>2.3.10</version.org.springframework.amqpboot>
```

2022-02-04 10:20 UTC, afalhambra commented on pom.xml
>      <version.org.springframework.amqpboot>2.3.4</version.org.springframework.amqpboot>
Done. Thanks!

2022-02-04 10:33 UTC, mareknovotny commented
jenkins do fdb

2022-02-04 10:33 UTC, mareknovotny approved these changes

2022-02-04 10:39 UTC, gmunozfe approved these changes
Looks good to me, well done @afalhambra !
As there's no 2.3.10 amqp-10-jms-spring-boot-starter, it seems correct to upgrade to the nearest 2.3.9.

2022-02-04 15:31 UTC, afalhambra commented
Failing test is not related

2022-02-04 19:05 UTC, afalhambra commented
@mareknovotny this should be ready to merge since failing test is not related

2022-02-07 07:57 UTC, mareknovotny commented
jenkins do fdb

2022-02-07 07:58 UTC, mareknovotny commented
waiting on FDB as the previous run didn't complete even with 1 failure not related ;) @afalhambra

2022-02-07 16:34 UTC, afalhambra commented
Same error again in the same test `org.kie.dmn.feel.client.showcase.FEELShowcaseIT.org.kie.dmn.feel.client.showcase.FEELShowcaseIT`

```
Error Message
io.github.bonigarcia.wdm.WebDriverManagerException: Error HTTP 404 executing GET http://npm.taobao.org/mirrors/geckodriver HTTP/1.1

Stacktrace
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: Error HTTP 404 executing GET http://npm.taobao.org/mirrors/geckodriver HTTP/1.1
	at org.kie.dmn.feel.client.showcase.FEELShowcaseIT.setupClass(FEELShowcaseIT.java:49)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: Error HTTP 404 executing GET http://npm.taobao.org/mirrors/geckodriver HTTP/1.1
	at org.kie.dmn.feel.client.showcase.FEELShowcaseIT.setupClass(FEELShowcaseIT.java:49)
```

Trying once more
Jenkins run fdb

2022-02-07 16:38 UTC, afalhambra commented
> FEELShowcaseIT

Running it once more, though I can see that even if that test got failed, the build keeps on going till it gets completed - am I wrong?

2022-02-08 07:40 UTC, mareknovotny commented
now it is ok, as the build is yellow on jenkins, so everything ran until the end ;).

2022-02-08 07:41 UTC, merged