upgrade build chain
kiegroup/droolsjbpm-build-bootstrap pull request #2187
Opened 2023-01-10 06:30 UTC by shubhbapna

Resolves https://github.com/kiegroup/github-action-build-chain/issues/325

Upgrade build-chain to latest tag

2023-01-10 08:24 UTC, Ginxo requested changes
@v3.0 can't be used here, since [Jenkinsfile.buildchain](https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/bbb34b2be08cedd09f93fcca7af0b8f2110dc473/.ci/jenkins/Jenkinsfile.buildchain#LL61C56-L61C99) (+ [buildChain.getBuildChainVersionFromCompositeActionFile](https://github.com/kiegroup/jenkins-pipeline-shared-libraries/blob/b353538411264cf71afcc9958088ed8f8d25e06c/vars/buildChain.groovy#L7)) will fail since v3.0 CLI is broken. New release + tag have to be released and point to it since https://github.com/kiegroup/github-action-build-chain/pull/332 has been merged after v3.0

2023-01-17 13:57 UTC, lampajr approved these changes

2023-01-19 07:25 UTC, Ginxo commented
I would fix https://github.com/kiegroup/github-action-build-chain/issues/358 before merging this

2023-01-25 18:27 UTC, merged

2023-01-26 11:03 UTC, mareknovotny commented
Just to be clear, this PR change was REVERTED @Ginxo @shubhbapna as suddenly CI on https://github.com/kiegroup/kie-soup/pull/264 failed with error:
```
Výstup na konzoli

Started by user [Marek](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/user/mnovotny)
Replayed [#95](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/kie-soup-main.pr/95/)
Loading library jenkins-pipeline-shared-libraries@main
Attempting to resolve main from remote references...
 > git --version # timeout=10
 > git --version # 'git version 2.31.1'
using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space
[INFO] Currently running in a labeled security context
 > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh16970542741045141007.key
Verifying host key using manually-configured host key entries
 > git ls-remote -h -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10
Found match: refs/heads/main revision b353538411264cf71afcc9958088ed8f8d25e06c
The recommended git tool is: NONE
using credential kie-ci-user-key
 > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/main/jobs/pullrequest/jobs/kie-soup-main.pr/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries
 > git --version # timeout=10
 > git --version # 'git version 2.31.1'
using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space
[INFO] Currently running in a labeled security context
 > /usr/bin/chcon --type=ssh_home_t /var/jenkins_home/jobs/KIE/jobs/main/jobs/pullrequest/jobs/kie-soup-main.pr/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh5143378218290024321.key
Verifying host key using manually-configured host key entries
 > git fetch --no-tags --force --progress -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10
Checking out Revision b353538411264cf71afcc9958088ed8f8d25e06c (main)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f b353538411264cf71afcc9958088ed8f8d25e06c # timeout=10
Commit message: "Do not specify location for maven settings (#243)"
 > git rev-list --no-walk b353538411264cf71afcc9958088ed8f8d25e06c # timeout=10
[Pipeline] Start of Pipeline
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor on ‘[kie-rhel7&&kie-mem4g&&!built-in](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/label/kie-rhel7&&kie-mem4g&&!built-in/)’
Running on [rhos-01-kie-rhel7-large-4](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/computer/rhos%2D01%2Dkie%2Drhel7%2Dlarge%2D4/) in /home/jenkins/workspace/KIE/main/pullrequest/kie-soup-main.pr
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
Selected Git installation does not exist. Using Default
Selected Git installation does not exist. Using Default
The recommended git tool is: NONE
using credential kie-ci
Cloning the remote Git repository
Cloning repository https://github.com/kiegroup/droolsjbpm-build-bootstrap/
 > git init /home/jenkins/workspace/KIE/main/pullrequest/kie-soup-main.pr # timeout=10
Fetching upstream changes from https://github.com/kiegroup/droolsjbpm-build-bootstrap/
 > git --version # timeout=10
 > git --version # 'git version 2.38.1'
using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space
 > git fetch --tags --force --progress -- https://github.com/kiegroup/droolsjbpm-build-bootstrap/ +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
Checking out Revision 1bd00f5eb8381ceda0f23dd9d7f6f1dc7321e4cb (refs/remotes/origin/main)
Commit message: "Bump jettison from 1.5.1 to 1.5.2 (#2182)"
First time build. Skipping changelog.
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] timestamps
[Pipeline] {
[Pipeline] timeout
11:31:58  Timeout set to expire in 2 hr 0 min
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Tool Install)
[Pipeline] tool
11:31:58  Installing NodeJS from /var/jenkins_home/caches/nodejs/LINUX/amd64/16.2.0.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0 on rhos-01-kie-rhel7-large-4
 > git config remote.origin.url https://github.com/kiegroup/droolsjbpm-build-bootstrap/ # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/main^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 1bd00f5eb8381ceda0f23dd9d7f6f1dc7321e4cb # timeout=10
[Pipeline] envVarsForTool
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Initialize)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] sh
11:32:01  + printenv
11:32:01  KEYCLOAK_SERVER_IP=bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com
11:32:01  ghprbPullId=264
11:32:01  PROPERTIES_GENERATOR_PATH=Tools/properties-generator
11:32:01  JENKINS_NODE_COOKIE=f0a8f8d1-2c8f-49bb-825d-1b5538a61ec4
11:32:01  XDG_SESSION_ID=1
11:32:01  BUILD_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/kie-soup-main.pr/96/
11:32:01  ghprbPullLink=https://github.com/kiegroup/kie-soup/pull/264
11:32:01  RHDM_PROPERTIES_GENERATOR_PATH=PROD/rhdm-properties-generator
11:32:01  HOSTNAME=eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com
11:32:01  OPENSTACK_PUBLIC_IP=10.0.169.167
11:32:01  SHELL=/bin/bash
11:32:01  HUDSON_SERVER_COOKIE=b8a1f8c21c9a8844
11:32:01  ghprbSourceBranch=pr-263
11:32:01  STAGE_NAME=Initialize
11:32:01  SSH_CLIENT=10.0.180.160 52666 22
11:32:01  BUILD_TAG=jenkins-KIE-main-pullrequest-kie-soup-main.pr-96
11:32:01  QUARKUS_CONTAINER_IMAGE_INSECURE=true
11:32:01  NPM_DOWNLOAD_ROOT=http://download.devel.redhat.com/rcm-guest/staging/rhba/dist/npm/
11:32:01  ghprbPullAuthorLogin=mareknovotny
11:32:01  BXMS_BINARIES_STORAGE=bxms-binaries.usersys.redhat.com
11:32:01  SRCCLR_INVOKER_REPO_URL=https://github.com/project-ncl/sourceclear-invoker
11:32:01  library.jenkins-pipeline-shared-libraries.version=main
11:32:01  ANT_HOME=/opt/tools/apache-ant-1.10.9
11:32:01  WORKSPACE=/home/jenkins/workspace/KIE/main/pullrequest/kie-soup-main.pr
11:32:01  JOB_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/kie-soup-main.pr/
11:32:01  RUN_CHANGES_DISPLAY_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/kie-soup-main.pr/96/display/redirect?page=changes
11:32:01  ghprbPullDescription=GitHub pull request #264 of commit bce456b980444a57d5a3437117d5189c622be989, no merge conflicts.
11:32:01  YARN_DOWNLOAD_ROOT=http://download.devel.redhat.com/rcm-guest/staging/rhba/dist/yarn/
11:32:01  CHECKSTYLE_FILE=**/checkstyle.log
11:32:01  PR_TYPE=Pull Request
11:32:01  ghprbAuthorRepoGitUrl=https://github.com/mareknovotny/kie-soup.git
11:32:01  USER=jenkins
11:32:01  JENKINS_CERT_FILE_PATH=/etc/openldap/cacerts/RH-IT-Root-CA.crt
11:32:01  BXMS_QE_NEXUS=https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus
11:32:01  ADDITIONAL_LABEL=kie-rhel7 && kie-mem4g && !built-in
11:32:01  JENKINS_NAME=eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com
11:32:01  RHPAM_PROPERTIES_GENERATOR_PATH=PROD/rhpam-properties-generator
11:32:01  QUARKUS_JIB_BASE_ [...]