Upgrade Kafka to address snappy-java vulnerabilities (CVE-2023-43642, CVE-2023-34455, ...)
kiegroup/droolsjbpm-build-bootstrap pull request #2445
Opened 2024-04-08 16:16 UTC by martinweiler

This upgrade to Kafka 3.6.0 will result in an update of the snappy-java dependency to 1.1.10.4 to address the following vulnerabilities:

https://nvd.nist.gov/vuln/detail/CVE-2023-34453
https://nvd.nist.gov/vuln/detail/CVE-2023-34454
https://nvd.nist.gov/vuln/detail/CVE-2023-34455
https://nvd.nist.gov/vuln/detail/CVE-2023-43642

2024-04-09 07:26 UTC, elguardian commented
Jenkins run fdb

2024-04-09 07:26 UTC, elguardian commented
@martinweiler let's wait for the fdb.

2024-07-11 17:39 UTC, akumar074 commented
Jenkins do fdb

2024-07-12 10:51 UTC, akumar074 commented
Jenkins run fdb

2024-07-15 07:13 UTC, elguardian approved these changes
LGTM

2024-07-15 07:13 UTC, elguardian commented
@gmunozfe have a look and merge whenever possible.

2024-07-16 08:11 UTC, mareknovotny commented
@martinweiler @elguardian @gmunozfe there are test failures 
- org.jbpm.workitem.springboot.samples.KafkaProxyAsyncSampleTest
- org.jbpm.workitem.springboot.samples.KafkaProxySampleTest

 related to this upgrade.
See 
`Doesn't know the specified Kafka version: 3.6.0. The supported Kafka versions are: [2.8.1, 3.0.0, 3.1.0]`

2024-07-16 08:12 UTC, mareknovotny requested changes
this version requires to fix also Kafka tests to know this version

2024-07-16 10:35 UTC, martinweiler commented
Thank you @mareknovotny - good catch. I have updated Kafka / Strimzi now to be aligned.

2024-07-16 11:46 UTC, mareknovotny commented
jenkins do fdb

2024-07-17 14:13 UTC, mareknovotny approved these changes

2024-07-17 14:18 UTC, merged